app/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("catalog", views.catalog, name="catalog"),
    path("accounts/", include("django.contrib.auth.urls")),
    # path('checkout/', views.checkout_view, name='checkout'),
    path("checked-out-books/", views.checked_out_books_view, name="checked_out_books"),
    path("checkin/", views.checkin_view, name="checkin"),
    path("accounts/create-account", views.create_account, name="create_account"),
    path("place-hold/<int:book_id>/", views.place_hold_view, name="place_hold"),
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("app.urls")),
    path("admin/", admin.site.urls),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User


class Admin(models.Model):
    admin_id = models.AutoField(primary_key=True)
    firstname = models.CharField(max_length=255, blank=True, null=True)
    lastname = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    user_id = models.CharField(max_length=255, blank=True, null=True)
    password = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "Admin"


class Book(models.Model):
    book_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, blank=True, null=True)
    author = models.CharField(max_length=255, blank=True, null=True)
    pub_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    publisher = models.CharField(max_length=255, blank=True, null=True)
    genre = models.CharField(max_length=255, blank=True, null=True)
    isbn = models.BigIntegerField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    on_hold = models.IntegerField(blank=True, null=True)
    hold_end = models.DateField(blank=True, null=True)
    checkout_date = models.DateField(blank=True, null=True)
    due_date = models.DateField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = "Book"


class Librarian(models.Model):
    librarian_id = models.AutoField(primary_key=True)
    firstname = models.CharField(max_length=255, blank=True, null=True)
    lastname = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    user_id = models.CharField(max_length=255, blank=True, null=True)
    password = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "Librarian"


class Patron(models.Model):
    patron_id = models.AutoField(primary_key=True)
    firstname = models.CharField(max_length=255, blank=True, null=True)
    lastname = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    user_id = models.CharField(max_length=255, blank=True, null=True)
    password = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "Patron"


class Fee(models.Model):
    fee_id = models.AutoField(primary_key=True)
    book = models.ForeignKey(Book, models.DO_NOTHING, blank=True, null=True)
    fee_amount = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )
    user_id = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "Fee"

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Library System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Library</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="btn-group" role="group" aria-label="Basic example">
          <a href="{% url 'index' %}" class="btn btn-primary">Home</a>
          <a href="{% url 'catalog' %}" class="btn btn-primary">Catalog</a>
          {% if user.is_authenticated %}
            <div class="btn-group" role="group">
              <button id="userDropdown" type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">User: {{ user.get_username }}</button>
              <ul class="dropdown-menu" aria-labelledby="userDropdown">
                <li>
                  <a class="dropdown-item" href="{% url 'checked_out_books' %}">Checked Out Books</a>
                </li>
                <li>
                  <form id="logout-form" method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="dropdown-item">Logout</button>
                  </form>
                </li>
              </ul>
            </div>
          {% else %}
            <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
            <a href="{% url 'create_account' %}" class="btn btn-primary">Create Account</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container mt-5">
      {% block content %}

      {% endblock %}
    </div>
    {% block script %}

    {% endblock %}
  </body>
</html>

templates/catalog.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
    <div class="col">
      <form id="checkout-form" method="post" action="{% url 'checked_out_books' %}">
        {% csrf_token %}
        <h1>Catalog</h1>
        <table id="book-data-table" class="table table-striped table-bordered" style="width:100%">
          <thead>
            <tr>
              {% if user.is_authenticated %}
                <th>Select</th>
              {% endif %}
              <th>Cover</th>
              <th>#</th>
              <th>Name</th>
              <th>Author</th>
              <th>Genre</th>
              <th>ISBN</th>
              <th>User</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {% for item in books %}
              <tr>
                {% if user.is_authenticated %}
                  <td>
                    <input type="checkbox" name="books" value="{{ item.book_id }}" />
                  </td>
                {% endif %}
                <td>
                  <img src="https://book-covers-public.s3.amazonaws.com/{{ item.isbn }}.jpg" alt="{{ item.title }}" style="width: 100px; height: 150px;" />
                </td>
                <td>{{ item.book_id }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.author }}</td>
                <td>{{ item.genre }}</td>
                <td>{{ item.isbn }}</td>
                <td>{{ item.user_id }}</td>
                <td>
                  {% if item.on_hold %}
                    <span class="badge bg-warning">On Hold</span>
                    {% if item.hold_end %}
                      <br />Hold Expires: {{ item.hold_end }}
                    {% endif %}
                  {% elif item.user_id %}
                    <span class="badge bg-secondary">Checked Out</span>
                  {% else %}
                    <a href="{% url 'place_hold' item.book_id %}" class="btn btn-primary">Place Hold</a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        {% if user.is_authenticated %}
          <button type="submit" form="checkout-form" class="btn btn-primary">Checkout</button>
        {% endif %}
      </form>

      {% comment %} <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div id="checkout-toast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
          <div class="toast-header">
            <strong class="me-auto">Checkout Success</strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
          <div class="toast-body">Books have been checked out successfully.</div>
        </div>
      </div>
    </div>
  </div> {% endcomment %}
{% endblock %}

{% block script %}
  <script>
    $(document).ready(function () {
      $('#book-data-table').DataTable()
    })
  </script>

  {% comment %} <script>
    $(document).ready(function () {
        $('#checkout-form').submit(function (event) {
            event.preventDefault();
            var form = $(this);
            $.ajax({
                type: form.attr('method'),
                url: form.attr('action'),
                data: form.serialize(),
                success: function (data) {
                    $('#checkout-toast').toast('show');
                },
                error: function (data) {
                }
            });
        });

        $('#checkout-toast').toast({
            delay: 2000
        });
    });
    </script> {% endcomment %}
{% endblock %}

templates/checked_out_books.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>Checked Out Books</h1>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Book</th>
            <th>Title</th>
            <th>Author</th>
            <th>Genre</th>
            <th>ISBN</th>
            <th>Due Date</th>
            <th>Fee</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for item in checked_out_books %}
            <tr>
              <td>
                <img src="https://book-covers-public.s3.amazonaws.com/{{ item.isbn }}.jpg" alt="{{ item.title }}" style="width: 100px; height: 150px;" />
              </td>
              <td>{{ item.title }}</td>
              <td>{{ item.author }}</td>
              <td>{{ item.genre }}</td>
              <td>{{ item.isbn }}</td>
              <td>{{ item.due_date|default:'Not set' }}</td>
              <td>{{ item.fee_set.first.fee_amount|default:'No fee' }}</td>
              <td>
                {% if item.fee_set.first.fee_amount > 0 %}
                  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#feeModal{{ item.book_id }}">Pay Fee</button>
                {% else %}
                  <form method="post" action="{% url 'checkin' %}">
                    {% csrf_token %}
                    <input type="hidden" name="book_id" value="{{ item.book_id }}" />
                    <button type="submit" class="btn btn-primary">Check In</button>
                  </form>
                {% endif %}
              </td>
            </tr>
            <!-- Fee Modal -->
            <div class="modal fade" id="feeModal{{ item.book_id }}" tabindex="-1" aria-labelledby="feeModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="feeModalLabel">Pay Fee</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <p>You have a fee of ${{ item.fee_set.first.fee_amount }} for '{{ item.title }}'. Please confirm that you want to pay the fee to check in the book.</p>
                  </div>
                  <div class="modal-footer">
                    <form id="payFeeForm{{ item.book_id }}" method="post" action="{% url 'checkin' %}">
                      {% csrf_token %}
                      <input type="hidden" name="book_id" value="{{ item.book_id }}" />
                      <button type="submit" class="btn btn-danger">Pay Fee</button>
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    $(document).ready(function () {
      $('#payFeeForm{{ item.book_id }}').submit(function (e) {
        e.preventDefault()
        var form = $(this)
        var url = form.attr('action')
    
        $.ajax({
          type: 'POST',
          url: url,
          data: form.serialize(),
          success: function (data) {
            // Reload the page or update the table to reflect the changes
            location.reload()
          },
          error: function (xhr, errmsg, err) {
            console.log(xhr.status + ': ' + xhr.responseText) // Log any errors
          }
        })
      })
    })
  </script>
{% endblock %}

templates/create_account.html
{% extends 'base.html' %}
{% block content %}
  <h1>Create Account</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
  </form>

  <h3>Already Have an Account??</h3>
  <a href="{% url 'login' %}">Sign In Here</a>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <img src="https://book-covers-public.s3.amazonaws.com/{{ book.isbn }}.jpg" class="card-img-top" alt="{{ book.title }}" />
          <div class="card-body text-center">
            <h5 class="card-title">{{ book.title }}</h5>
            <p class="card-text">Author: {{ book.author }}</p>
            <p class="card-text">Genre: {{ book.genre }}</p>
            <p class="card-text">ISBN: {{ book.isbn }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Book Description</h5>
            <p class="card-text">{{ book.description }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
  <div class="container page-form">
    <form action="/" id="" method="POST">
      <div class="form-group">
        <h1>Hello Stranger!</h1>
        <div class="row">
          <div class="col-4">
            <input class="form-control" id="username" name="username" type="text" placeholder="Input your username" />
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <input class="form-control" id="password" name="password" type="password" placeholder="Input your password" />
          </div>
        </div>
      </div>
      <button class="btn btn-success" type="submit">Login</button>
    </form>
  </div>
  <div class="page-header"></div>
{% endblock %}